#!/usr/bin/env python3
"""
Migrated from: run-test-vm.sh
Auto-generated Python - 2025-08-16T04:57:27.585Z
"""

import os
import sys
import subprocess
import shutil
import glob
from pathlib import Path

def main():
    # QEMU run script for test-vm
    # Generated by EnvironmentSetupService
    subprocess.run("qemu-system-x86_64 \", shell=True)
    subprocess.run("-name \", shell=True)
    subprocess.run("test-vm \", shell=True)
    subprocess.run("-m \", shell=True)
    subprocess.run("2G \", shell=True)
    subprocess.run("-smp \", shell=True)
    subprocess.run("2 \", shell=True)
    subprocess.run("-cpu \", shell=True)
    subprocess.run("host \", shell=True)
    subprocess.run("-enable-kvm \", shell=True)
    subprocess.run("-netdev \", shell=True)
    subprocess.run("user,id=net0,hostfwd=tcp::6665-:22,hostfwd=tcp::8080-:80,hostfwd=tcp::8443-:443,hostfwd=tcp::9000-:9000,hostfwd=tcp::9001-:9001,hostfwd=tcp::9002-:9002,hostfwd=tcp::9003-:9003,hostfwd=tcp::9004-:9004,hostfwd=tcp::9005-:9005,hostfwd=tcp::9006-:9006,hostfwd=tcp::9007-:9007,hostfwd=tcp::9008-:9008,hostfwd=tcp::9009-:9009,hostfwd=tcp::9010-:9010 \", shell=True)
    subprocess.run("-device \", shell=True)
    subprocess.run("virtio-net,netdev=net0 \", shell=True)
    subprocess.run("-gdb \", shell=True)
    subprocess.run("tcp::1234 \", shell=True)
    subprocess.run("-virtfs \", shell=True)
    subprocess.run("local,path=/home/ormastes/dev/aidev/layer/themes/init_setup-folder/.setup/shared,mount_tag=share,security_model=none,id=share-folder", shell=True)
    print("QEMU instance 'test-vm' started")
    print("Ports:")
    print("  ssh: 6665")
    print("  http: 8080")
    print("  https: 8443")
    print("  debug: 9000")
    print("  gdb: 1234")

if __name__ == "__main__":
    main()