#!/usr/bin/env python3
"""
Migrated from: complete-demo.sh
Auto-generated Python - 2025-08-16T04:57:27.680Z
"""

import os
import sys
import subprocess
import shutil
import glob
from pathlib import Path

def main():
    # Complete demo script for Mate Dealer with GUI Selector integration
    subprocess.run("set -e", shell=True)
    print("=== Mate Dealer + GUI Selector Complete Demo ===")
    print("")
    # Colors for output
    subprocess.run("GREEN='\033[0;32m'", shell=True)
    subprocess.run("BLUE='\033[0;34m'", shell=True)
    subprocess.run("YELLOW='\033[1;33m'", shell=True)
    subprocess.run("NC='\033[0m' # No Color", shell=True)
    # Paths
    subprocess.run("SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"", shell=True)
    subprocess.run("PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"", shell=True)
    subprocess.run("GUI_SELECTOR_DIR="$PROJECT_ROOT/layer/themes/gui-selector/user-stories/023-gui-selector-server"", shell=True)
    subprocess.run("MATE_DEALER_DIR="$PROJECT_ROOT/scripts/setup/demo/mate-dealer"", shell=True)
    # Step 1: Start GUI Selector Server
    print("-e ")${BLUE}Step 1: Starting GUI Selector Server${NC}"
    subprocess.run("if ! curl -s http://localhost:3456/api/health > /dev/null 2>&1; then", shell=True)
    print("Starting GUI Selector on port 3456...")
    os.chdir(""$GUI_SELECTOR_DIR"")
    subprocess.run("NODE_ENV=release PORT=3456 npm start > /tmp/gui-selector.log 2>&1 &", shell=True)
    subprocess.run("GUI_PID=$!", shell=True)
    time.sleep(5)
    else:
    print("GUI Selector already running on port 3456")
    # Step 2: Check Mate Dealer Demo
    print("-e ")${BLUE}Step 2: Checking Mate Dealer Demo${NC}"
    os.chdir(""$MATE_DEALER_DIR"")
    # Install Playwright browsers if not already installed
    print("Installing Playwright browsers...")
    subprocess.run("bunx playwright install chromium", shell=True)
    # Step 3: Create a simple mate dealer app
    print("-e ")${BLUE}Step 3: Creating Mate Dealer Application${NC}"
    # Create basic HTML file
    subprocess.run("cat > public/index.html << 'EOF'", shell=True)
    subprocess.run("<!DOCTYPE html>", shell=True)
    subprocess.run("<html lang="en">", shell=True)
    subprocess.run("<head>", shell=True)
    subprocess.run("<meta charset="UTF-8">", shell=True)
    subprocess.run("<meta name="viewport" content="width=device-width, initial-scale=1.0">", shell=True)
    subprocess.run("<title>Mate Dealer - Marketplace</title>", shell=True)
    subprocess.run("<link rel="stylesheet" href="/css/theme.css">", shell=True)
    subprocess.run("<style>", shell=True)
    subprocess.run("body {", shell=True)
    subprocess.run("font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;", shell=True)
    subprocess.run("margin: 0;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("background-color: #f5f5f5;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".container {", shell=True)
    subprocess.run("max-width: 1200px;", shell=True)
    subprocess.run("margin: 0 auto;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".login-form {", shell=True)
    subprocess.run("max-width: 400px;", shell=True)
    subprocess.run("margin: 50px auto;", shell=True)
    subprocess.run("padding: 30px;", shell=True)
    subprocess.run("background: white;", shell=True)
    subprocess.run("border-radius: 10px;", shell=True)
    subprocess.run("box-shadow: 0 2px 10px rgba(0,0,0,0.1);", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".role-selector {", shell=True)
    subprocess.run("display: flex;", shell=True)
    subprocess.run("gap: 20px;", shell=True)
    subprocess.run("margin-bottom: 20px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("input[type="email"], input[type="password"] {", shell=True)
    subprocess.run("width: 100%;", shell=True)
    subprocess.run("padding: 10px;", shell=True)
    subprocess.run("margin: 10px 0;", shell=True)
    subprocess.run("border: 1px solid #ddd;", shell=True)
    subprocess.run("border-radius: 5px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("button {", shell=True)
    subprocess.run("width: 100%;", shell=True)
    subprocess.run("padding: 12px;", shell=True)
    subprocess.run("background: #2563eb;", shell=True)
    subprocess.run("color: white;", shell=True)
    subprocess.run("border: none;", shell=True)
    subprocess.run("border-radius: 5px;", shell=True)
    subprocess.run("cursor: pointer;", shell=True)
    subprocess.run("font-size: 16px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("button:hover {", shell=True)
    subprocess.run("background: #1d4ed8;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".dealer-card {", shell=True)
    subprocess.run("background: white;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("margin: 10px 0;", shell=True)
    subprocess.run("border-radius: 8px;", shell=True)
    subprocess.run("box-shadow: 0 2px 5px rgba(0,0,0,0.1);", shell=True)
    subprocess.run("cursor: pointer;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".dealer-card:hover {", shell=True)
    subprocess.run("box-shadow: 0 4px 10px rgba(0,0,0,0.15);", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".dashboard {", shell=True)
    subprocess.run("display: none;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".dashboard.active {", shell=True)
    subprocess.run("display: block;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("</style>", shell=True)
    subprocess.run("</head>", shell=True)
    subprocess.run("<body>", shell=True)
    subprocess.run("<div class="container">", shell=True)
    subprocess.run("<!-- Login Form -->", shell=True)
    subprocess.run("<div id="loginForm" class="login-form">", shell=True)
    subprocess.run("<h1>Mate Dealer Login</h1>", shell=True)
    subprocess.run("<div class="role-selector">", shell=True)
    subprocess.run("<label>", shell=True)
    subprocess.run("<input type="radio" name="role" value="customer" checked> Customer", shell=True)
    subprocess.run("</label>", shell=True)
    subprocess.run("<label>", shell=True)
    subprocess.run("<input type="radio" name="role" value="dealer"> Dealer", shell=True)
    subprocess.run("</label>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<input type="email" name="email" placeholder="Email" value="demo@example.com">", shell=True)
    subprocess.run("<input type="password" name="password" placeholder="Password" value="demo123">", shell=True)
    subprocess.run("<button type="submit" onclick="login()">Login</button>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<!-- Customer Dashboard -->", shell=True)
    subprocess.run("<div id="customerDashboard" class="dashboard">", shell=True)
    subprocess.run("<h1>Find Your Perfect Mate Dealer</h1>", shell=True)
    subprocess.run("<div id="dealerList">", shell=True)
    subprocess.run("<div class="dealer-card" onclick="viewDealer('Juan\'s Mate Shop')">", shell=True)
    subprocess.run("<h3>Juan's Mate Shop</h3>", shell=True)
    subprocess.run("<p>Distance: 2.3 km | Rating: ⭐⭐⭐⭐⭐</p>", shell=True)
    subprocess.run("<p>Specialties: Traditional Argentine Mate, Organic Options</p>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="dealer-card" onclick="viewDealer('Maria\'s Traditional Mate')">", shell=True)
    subprocess.run("<h3>Maria's Traditional Mate</h3>", shell=True)
    subprocess.run("<p>Distance: 3.1 km | Rating: ⭐⭐⭐⭐</p>", shell=True)
    subprocess.run("<p>Specialties: Flavored Mate, Accessories</p>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<button onclick="logout()">Logout</button>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<!-- Dealer Dashboard -->", shell=True)
    subprocess.run("<div id="dealerDashboard" class="dashboard">", shell=True)
    subprocess.run("<h1>Dealer Dashboard</h1>", shell=True)
    subprocess.run("<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">", shell=True)
    subprocess.run("<div class="dealer-card">", shell=True)
    subprocess.run("<h3>Total Customers</h3>", shell=True)
    subprocess.run("<p style="font-size: 2em; margin: 0;">24</p>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="dealer-card">", shell=True)
    subprocess.run("<h3>Active Orders</h3>", shell=True)
    subprocess.run("<p style="font-size: 2em; margin: 0;">5</p>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="dealer-card">", shell=True)
    subprocess.run("<h3>Revenue This Month</h3>", shell=True)
    subprocess.run("<p style="font-size: 2em; margin: 0;">$3,450</p>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<button onclick="logout()">Logout</button>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<script>", shell=True)
    subprocess.run("function login() {", shell=True)
    subprocess.run("const role = document.querySelector('input[name="role"]:checked').value;", shell=True)
    subprocess.run("document.getElementById('loginForm').style.display = 'none';", shell=True)
    subprocess.run("if (role === 'customer') {", shell=True)
    subprocess.run("document.getElementById('customerDashboard').classList.add('active');", shell=True)
    subprocess.run("} else {", shell=True)
    subprocess.run("document.getElementById('dealerDashboard').classList.add('active');", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("function logout() {", shell=True)
    subprocess.run("document.querySelectorAll('.dashboard').forEach(d => d.classList.remove('active'));", shell=True)
    subprocess.run("document.getElementById('loginForm').style.display = 'block';", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("function viewDealer(name) {", shell=True)
    subprocess.run("alert('Viewing details for: ' + name);", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("</script>", shell=True)
    subprocess.run("</body>", shell=True)
    subprocess.run("</html>", shell=True)
    subprocess.run("EOF", shell=True)
    # Step 4: GUI Selector Integration Demo
    print("-e ")${BLUE}Step 4: GUI Selector Integration${NC}"
    print("-e ")${YELLOW}Manual Steps:${NC}"
    print("1. Open GUI Selector: http://localhost:3456")
    print("2. Login with: admin / admin123")
    print("3. Browse the 4 template options:")
    print("   - Modern Dashboard (Clean, minimalist)")
    print("   - Corporate Portal (Professional, business)")
    print("   - Artistic Showcase (Creative, bold)")
    print("   - Universal Access (Accessible, WCAG compliant)")
    print("4. Click on a template to preview")
    print("5. Click 'Select This Template'")
    print("6. Enter project name: 'Mate Dealer App'")
    print("")
    # Step 5: Start Mate Dealer Server
    print("-e ")${BLUE}Step 5: Starting Mate Dealer Demo Server${NC}"
    os.chdir(""$MATE_DEALER_DIR"")
    # Create simple server
    subprocess.run("cat > src/demo-server.ts << 'EOF'", shell=True)
    subprocess.run("import express from 'express';", shell=True)
    subprocess.run("import path from 'path';", shell=True)
    subprocess.run("const app = express();", shell=True)
    subprocess.run("const PORT = 3303;", shell=True)
    subprocess.run("app.use(express.static(path.join(__dirname, '../public')));", shell=True)
    subprocess.run("app.get('/api/health', (req, res) => {", shell=True)
    subprocess.run("res.json({ status: 'healthy', service: 'mate-dealer' });", shell=True)
    subprocess.run("});", shell=True)
    subprocess.run("app.listen(PORT, () => {", shell=True)
    subprocess.run("console.log(`Mate Dealer running on http://localhost:${PORT}`);", shell=True)
    subprocess.run("});", shell=True)
    subprocess.run("EOF", shell=True)
    # Start the server
    print("Starting Mate Dealer on port 3303...")
    subprocess.run("bunx ts-node src/demo-server.ts > /tmp/mate-dealer.log 2>&1 &", shell=True)
    subprocess.run("MATE_PID=$!", shell=True)
    time.sleep(3)
    # Step 6: Run E2E Tests
    print("-e ")${BLUE}Step 6: Running E2E Tests${NC}"
    print("Running click-based E2E tests...")
    # Create a simple test runner
    subprocess.run("cat > run-e2e-demo.js << 'EOF'", shell=True)
    subprocess.run("const { chromium } = require('playwright');", shell=True)
    subprocess.run("async function runDemo() {", shell=True)
    subprocess.run("const browser = await chromium.launch({ headless: false, slowMo: 500 });", shell=True)
    subprocess.run("const context = await browser.newContext();", shell=True)
    subprocess.run("const page = await context.newPage();", shell=True)
    subprocess.run("console.log('📱 Testing Mate Dealer App...');", shell=True)
    subprocess.run("// Go to app", shell=True)
    subprocess.run("await page.goto('http://localhost:3303');", shell=True)
    subprocess.run("console.log('✓ Loaded Mate Dealer');", shell=True)
    subprocess.run("// Test customer flow", shell=True)
    subprocess.run("await page.click('input[value="customer"]');", shell=True)
    subprocess.run("await page.fill('input[name="email"]', 'test@example.com');", shell=True)
    subprocess.run("await page.fill('input[name="password"]', 'demo123');", shell=True)
    subprocess.run("await page.click('button[type="submit"]');", shell=True)
    subprocess.run("console.log('✓ Logged in as customer');", shell=True)
    subprocess.run("// Click on dealer", shell=True)
    subprocess.run("await page.waitForTimeout(1000);", shell=True)
    subprocess.run("await page.click('.dealer-card:first-child');", shell=True)
    subprocess.run("console.log('✓ Clicked on dealer');", shell=True)
    subprocess.run("// Logout", shell=True)
    subprocess.run("await page.click('button:has-text("Logout")');", shell=True)
    subprocess.run("console.log('✓ Logged out');", shell=True)
    subprocess.run("// Test dealer flow", shell=True)
    subprocess.run("await page.click('input[value="dealer"]');", shell=True)
    subprocess.run("await page.click('button[type="submit"]');", shell=True)
    subprocess.run("console.log('✓ Logged in as dealer');", shell=True)
    subprocess.run("await page.waitForTimeout(2000);", shell=True)
    subprocess.run("console.log('✅ E2E Demo completed!');", shell=True)
    subprocess.run("await browser.close();", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("runDemo().catch(console.error);", shell=True)
    subprocess.run("EOF", shell=True)
    subprocess.run("node run-e2e-demo.js", shell=True)
    # Summary
    print("")
    print("-e ")${GREEN}=== Demo Complete! ===${NC}"
    print("")
    print("Summary:")
    print("✓ GUI Selector Server running on http://localhost:3456")
    print("✓ Mate Dealer Demo running on http://localhost:3303")
    print("✓ E2E tests demonstrate click-based interactions")
    print("✓ Template selection available via GUI Selector")
    print("")
    print("Key Features Demonstrated:")
    print("- User role selection (Customer/Dealer)")
    print("- Login functionality")
    print("- Customer dashboard with dealer listings")
    print("- Dealer dashboard with business metrics")
    print("- GUI template selection integration")
    print("- Click-based E2E testing")
    print("")
    print("To stop servers:")
    print("kill $GUI_PID $MATE_PID")
    # Cleanup function
    subprocess.run("cleanup() {", shell=True)
    print("Cleaning up...")
    subprocess.run("kill $GUI_PID $MATE_PID 2>/dev/null || true", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("trap cleanup EXIT", shell=True)
    print("")
    print("Press Ctrl+C to stop the demo...")
    subprocess.run("wait", shell=True)

if __name__ == "__main__":
    main()