#!/usr/bin/env python3
"""
Migrated from: generate-report.sh
Auto-generated Python - 2025-08-16T04:57:27.693Z
"""

import os
import sys
import subprocess
import shutil
import glob
from pathlib import Path

def main():
    # Generate final HTML report from test results
    subprocess.run("SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"", shell=True)
    subprocess.run("RESULTS_DIR="$(dirname "$SCRIPT_DIR")/results"", shell=True)
    subprocess.run("REPORT_FILE="$RESULTS_DIR/test-report.html"", shell=True)
    print("📄 Generating HTML report...")
    # Start HTML document
    subprocess.run("cat > "$REPORT_FILE" << 'EOF'", shell=True)
    subprocess.run("<!DOCTYPE html>", shell=True)
    subprocess.run("<html lang="en">", shell=True)
    subprocess.run("<head>", shell=True)
    subprocess.run("<meta charset="UTF-8">", shell=True)
    subprocess.run("<meta name="viewport" content="width=device-width, initial-scale=1.0">", shell=True)
    subprocess.run("<title>MCP Docker Test Report</title>", shell=True)
    subprocess.run("<style>", shell=True)
    subprocess.run("body {", shell=True)
    subprocess.run("font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;", shell=True)
    subprocess.run("line-height: 1.6;", shell=True)
    subprocess.run("color: #333;", shell=True)
    subprocess.run("max-width: 1200px;", shell=True)
    subprocess.run("margin: 0 auto;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("background-color: #f5f5f5;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("h1 {", shell=True)
    subprocess.run("color: #2c3e50;", shell=True)
    subprocess.run("border-bottom: 3px solid #3498db;", shell=True)
    subprocess.run("padding-bottom: 10px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("h2 {", shell=True)
    subprocess.run("color: #34495e;", shell=True)
    subprocess.run("margin-top: 30px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".summary {", shell=True)
    subprocess.run("background: white;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("border-radius: 8px;", shell=True)
    subprocess.run("box-shadow: 0 2px 4px rgba(0,0,0,0.1);", shell=True)
    subprocess.run("margin-bottom: 30px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".stats {", shell=True)
    subprocess.run("display: grid;", shell=True)
    subprocess.run("grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));", shell=True)
    subprocess.run("gap: 20px;", shell=True)
    subprocess.run("margin-top: 20px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".stat-card {", shell=True)
    subprocess.run("background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);", shell=True)
    subprocess.run("color: white;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("border-radius: 8px;", shell=True)
    subprocess.run("text-align: center;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".stat-value {", shell=True)
    subprocess.run("font-size: 2em;", shell=True)
    subprocess.run("font-weight: bold;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".stat-label {", shell=True)
    subprocess.run("font-size: 0.9em;", shell=True)
    subprocess.run("opacity: 0.9;", shell=True)
    subprocess.run("margin-top: 5px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".mode-results {", shell=True)
    subprocess.run("background: white;", shell=True)
    subprocess.run("padding: 20px;", shell=True)
    subprocess.run("border-radius: 8px;", shell=True)
    subprocess.run("box-shadow: 0 2px 4px rgba(0,0,0,0.1);", shell=True)
    subprocess.run("margin-bottom: 20px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".pass {", shell=True)
    subprocess.run("color: #27ae60;", shell=True)
    subprocess.run("font-weight: bold;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".fail {", shell=True)
    subprocess.run("color: #e74c3c;", shell=True)
    subprocess.run("font-weight: bold;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".warning {", shell=True)
    subprocess.run("color: #f39c12;", shell=True)
    subprocess.run("font-weight: bold;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("table {", shell=True)
    subprocess.run("width: 100%;", shell=True)
    subprocess.run("border-collapse: collapse;", shell=True)
    subprocess.run("margin-top: 10px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("th, td {", shell=True)
    subprocess.run("padding: 10px;", shell=True)
    subprocess.run("text-align: left;", shell=True)
    subprocess.run("border-bottom: 1px solid #ddd;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("th {", shell=True)
    subprocess.run("background-color: #f8f9fa;", shell=True)
    subprocess.run("font-weight: 600;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".timestamp {", shell=True)
    subprocess.run("color: #7f8c8d;", shell=True)
    subprocess.run("font-size: 0.9em;", shell=True)
    subprocess.run("margin-top: 30px;", shell=True)
    subprocess.run("text-align: center;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".violation-badge {", shell=True)
    subprocess.run("display: inline-block;", shell=True)
    subprocess.run("padding: 2px 8px;", shell=True)
    subprocess.run("border-radius: 4px;", shell=True)
    subprocess.run("font-size: 0.85em;", shell=True)
    subprocess.run("margin: 2px;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".violation-error {", shell=True)
    subprocess.run("background-color: #ff4757;", shell=True)
    subprocess.run("color: white;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".violation-warning {", shell=True)
    subprocess.run("background-color: #ffa502;", shell=True)
    subprocess.run("color: white;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run(".violation-info {", shell=True)
    subprocess.run("background-color: #3742fa;", shell=True)
    subprocess.run("color: white;", shell=True)
    subprocess.run("}", shell=True)
    subprocess.run("</style>", shell=True)
    subprocess.run("</head>", shell=True)
    subprocess.run("<body>", shell=True)
    subprocess.run("<h1>🧪 MCP Docker Test Report</h1>", shell=True)
    subprocess.run("EOF", shell=True)
    # Read summary data
    if -f "$RESULTS_DIR/summary.json" :; then
    subprocess.run("total_tests=$(jq -r '.statistics.totalTests // 0' "$RESULTS_DIR/summary.json")", shell=True)
    subprocess.run("total_passed=$(jq -r '.statistics.totalPassed // 0' "$RESULTS_DIR/summary.json")", shell=True)
    subprocess.run("total_failed=$(jq -r '.statistics.totalFailed // 0' "$RESULTS_DIR/summary.json")", shell=True)
    subprocess.run("pass_rate=$(jq -r '.statistics.passRate // 0' "$RESULTS_DIR/summary.json")", shell=True)
    else:
    subprocess.run("total_tests=0", shell=True)
    subprocess.run("total_passed=0", shell=True)
    subprocess.run("total_failed=0", shell=True)
    subprocess.run("pass_rate=0", shell=True)
    # Add summary section
    subprocess.run("cat >> "$REPORT_FILE" << EOF", shell=True)
    subprocess.run("<div class="summary">", shell=True)
    subprocess.run("<h2>Test Summary</h2>", shell=True)
    subprocess.run("<div class="stats">", shell=True)
    subprocess.run("<div class="stat-card">", shell=True)
    subprocess.run("<div class="stat-value">$total_tests</div>", shell=True)
    subprocess.run("<div class="stat-label">Total Tests</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="stat-card" style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);">", shell=True)
    subprocess.run("<div class="stat-value">$total_passed</div>", shell=True)
    subprocess.run("<div class="stat-label">Passed</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="stat-card" style="background: linear-gradient(135deg, #eb3349 0%, #f45c43 100%);">", shell=True)
    subprocess.run("<div class="stat-value">$total_failed</div>", shell=True)
    subprocess.run("<div class="stat-label">Failed</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("<div class="stat-card" style="background: linear-gradient(135deg, #FC466B 0%, #3F5EFB 100%);">", shell=True)
    subprocess.run("<div class="stat-value">${pass_rate}%</div>", shell=True)
    subprocess.run("<div class="stat-label">Pass Rate</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("EOF", shell=True)
    # Add results for each mode
    for mode in [strict enhanced basic; do]:
    subprocess.run("latest=$(ls -t "$RESULTS_DIR"/mcp-test-$mode-*.json 2>/dev/null | head -1)", shell=True)
    if -f "$latest" :; then
    subprocess.run("mode_tests=$(jq -r '.summary.totalTests // 0' "$latest")", shell=True)
    subprocess.run("mode_passed=$(jq -r '.summary.totalPassed // 0' "$latest")", shell=True)
    subprocess.run("mode_failed=$(jq -r '.summary.totalFailed // 0' "$latest")", shell=True)
    subprocess.run("mode_rate=$(jq -r '.summary.passRate // 0' "$latest")", shell=True)
    subprocess.run("cat >> "$REPORT_FILE" << EOF", shell=True)
    subprocess.run("<div class="mode-results">", shell=True)
    subprocess.run("<h2>${mode^^} Mode Results</h2>", shell=True)
    subprocess.run("<table>", shell=True)
    subprocess.run("<tr>", shell=True)
    subprocess.run("<th>Metric</th>", shell=True)
    subprocess.run("<th>Value</th>", shell=True)
    subprocess.run("<th>Status</th>", shell=True)
    subprocess.run("</tr>", shell=True)
    subprocess.run("<tr>", shell=True)
    subprocess.run("<td>Total Tests</td>", shell=True)
    subprocess.run("<td>$mode_tests</td>", shell=True)
    subprocess.run("<td>-</td>", shell=True)
    subprocess.run("</tr>", shell=True)
    subprocess.run("<tr>", shell=True)
    subprocess.run("<td>Passed</td>", shell=True)
    subprocess.run("<td>$mode_passed</td>", shell=True)
    subprocess.run("<td class="pass">✅</td>", shell=True)
    subprocess.run("</tr>", shell=True)
    subprocess.run("<tr>", shell=True)
    subprocess.run("<td>Failed</td>", shell=True)
    subprocess.run("<td>$mode_failed</td>", shell=True)
    subprocess.run("<td class="fail">$([ $mode_failed -gt 0 ] && echo "❌" || echo "✅")</td>", shell=True)
    subprocess.run("</tr>", shell=True)
    subprocess.run("<tr>", shell=True)
    subprocess.run("<td>Pass Rate</td>", shell=True)
    subprocess.run("<td>${mode_rate}%</td>", shell=True)
    subprocess.run("<td class="$([ $mode_rate -ge 80 ] && echo "pass" || echo "warning")">", shell=True)
    subprocess.run("$([ $mode_rate -ge 80 ] && echo "✅" || echo "⚠️")", shell=True)
    subprocess.run("</td>", shell=True)
    subprocess.run("</tr>", shell=True)
    subprocess.run("</table>", shell=True)
    subprocess.run("EOF", shell=True)
    # Add violation details if available
    subprocess.run("violations=$(ls -t "$RESULTS_DIR"/violations-*.json 2>/dev/null | head -1)", shell=True)
    if -f "$violations" :; then
    subprocess.run("cat >> "$REPORT_FILE" << EOF", shell=True)
    subprocess.run("<h3>Violations Detected</h3>", shell=True)
    subprocess.run("<div>", shell=True)
    subprocess.run("EOF", shell=True)
    subprocess.run("jq -r '.byType | to_entries[] | "<span class=\"violation-badge violation-\(.value.severity)\">\(.key): \(.value.count)</span>"' "$violations" >> "$REPORT_FILE" 2>/dev/null || true", shell=True)
    subprocess.run("cat >> "$REPORT_FILE" << EOF", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("EOF", shell=True)
    print("    </div>") >> "$REPORT_FILE"
    # Add timestamp
    subprocess.run("cat >> "$REPORT_FILE" << EOF", shell=True)
    subprocess.run("<div class="timestamp">", shell=True)
    subprocess.run("Report generated: $(date)", shell=True)
    subprocess.run("</div>", shell=True)
    subprocess.run("</body>", shell=True)
    subprocess.run("</html>", shell=True)
    subprocess.run("EOF", shell=True)
    print("✅ HTML report generated: $REPORT_FILE")
    # Open report if possible
    subprocess.run("if command -v xdg-open &> /dev/null; then", shell=True)
    print("Opening report in browser...")
    subprocess.run("xdg-open "$REPORT_FILE"", shell=True)
    subprocess.run("elif command -v open &> /dev/null; then", shell=True)
    print("Opening report in browser...")
    subprocess.run("open "$REPORT_FILE"", shell=True)
    else:
    print("Report available at: $REPORT_FILE")

if __name__ == "__main__":
    main()