#!/bin/bash
# QEMU run script for test-vm
# Generated by EnvironmentSetupService

qemu-system-x86_64 \
  -name \
  test-vm \
  -m \
  2G \
  -smp \
  2 \
  -cpu \
  host \
  -enable-kvm \
  -netdev \
  user,id=net0,hostfwd=tcp::6665-:22,hostfwd=tcp::8080-:80,hostfwd=tcp::8443-:443,hostfwd=tcp::9000-:9000,hostfwd=tcp::9001-:9001,hostfwd=tcp::9002-:9002,hostfwd=tcp::9003-:9003,hostfwd=tcp::9004-:9004,hostfwd=tcp::9005-:9005,hostfwd=tcp::9006-:9006,hostfwd=tcp::9007-:9007,hostfwd=tcp::9008-:9008,hostfwd=tcp::9009-:9009,hostfwd=tcp::9010-:9010 \
  -device \
  virtio-net,netdev=net0 \
  -gdb \
  tcp::1234 \
  -virtfs \
  local,path=/home/ormastes/dev/aidev/layer/themes/init_setup-folder/.setup/shared,mount_tag=share,security_model=none,id=share-folder

echo "QEMU instance 'test-vm' started"
echo "Ports:"
echo "  ssh: 6665"
echo "  http: 8080"
echo "  https: 8443"
echo "  debug: 9000"
echo "  gdb: 1234"
