apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aidev-platform-dev

bases:
  - ../../base

namePrefix: dev-
nameSuffix: ""

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: env-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - RATE_LIMIT_MAX_REQUESTS=1000

replicas:
  - name: api-gateway
    count: 1
  - name: portal
    count: 1
  - name: monitoring-dashboard
    count: 1