apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-dashboard
  namespace: aidev-platform
  labels:
    app: monitoring-dashboard
    component: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-dashboard
  template:
    metadata:
      labels:
        app: monitoring-dashboard
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3999"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: monitoring-dashboard
        image: aidev/monitoring-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3999
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3999"
        - name: PROMETHEUS_PORT
          value: "9464"
        - name: INFLUXDB_URL
          value: "http://influxdb-service:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: token
        - name: JAEGER_ENDPOINT
          value: "http://jaeger-collector:14268/api/traces"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3999
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3999
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: aidev-platform
  labels:
    app: monitoring-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 3999
    targetPort: 3999
    protocol: TCP
    name: http
  - port: 9464
    targetPort: 9464
    protocol: TCP
    name: prometheus
  selector:
    app: monitoring-dashboard