#!/usr/bin/env bun
/**
 * Migrated from: run-test-vm.sh
 * Auto-generated TypeScript - 2025-08-16T04:57:27.585Z
 */

import { readFile, writeFile, mkdir, rm, copyFile, rename, access } from 'fs/promises';
import { join, dirname, basename, resolve } from 'path';
import { existsSync } from 'fs';
import { $ } from 'bun';

async function main() {
  // QEMU run script for test-vm
  // Generated by EnvironmentSetupService
  await $`qemu-system-x86_64 \`;
  await $`-name \`;
  await $`test-vm \`;
  await $`-m \`;
  await $`2G \`;
  await $`-smp \`;
  await $`2 \`;
  await $`-cpu \`;
  await $`host \`;
  await $`-enable-kvm \`;
  await $`-netdev \`;
  await $`user,id=net0,hostfwd=tcp::6665-:22,hostfwd=tcp::8080-:80,hostfwd=tcp::8443-:443,hostfwd=tcp::9000-:9000,hostfwd=tcp::9001-:9001,hostfwd=tcp::9002-:9002,hostfwd=tcp::9003-:9003,hostfwd=tcp::9004-:9004,hostfwd=tcp::9005-:9005,hostfwd=tcp::9006-:9006,hostfwd=tcp::9007-:9007,hostfwd=tcp::9008-:9008,hostfwd=tcp::9009-:9009,hostfwd=tcp::9010-:9010 \`;
  await $`-device \`;
  await $`virtio-net,netdev=net0 \`;
  await $`-gdb \`;
  await $`tcp::1234 \`;
  await $`-virtfs \`;
  await $`local,path=/home/ormastes/dev/aidev/layer/themes/init_setup-folder/.setup/shared,mount_tag=share,security_model=none,id=share-folder`;
  console.log("QEMU instance 'test-vm' started");
  console.log("Ports:");
  console.log("  ssh: 6665");
  console.log("  http: 8080");
  console.log("  https: 8443");
  console.log("  debug: 9000");
  console.log("  gdb: 1234");
}

// Run main
if (import.meta.main) {
  main().catch(console.error);
}