version: 3.8
services:
  portal:
    image: aidev/test-app:latest
    ports:
      - 3100:3100
    environment:
      - NODE_ENV=test
      - PORT=3100
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
