#!/usr/bin/env ts-node

/**
 * Script to generate manual documentation from test files across all themes
 * Uses the infra_test-as-manual theme's ManualGenerator
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  ManualGenerator,
  ThemeScanner,
  ThemeRegistry,
  ManualGeneratorOptions,
  GeneratedManual
} from '../layer/themes/infra_test-as-manual/pipe';

const THEMES_DIR = path.join(__dirname, '..', 'layer', 'themes');
const OUTPUT_DIR = path.join(__dirname, '..', 'gen', 'test-manuals');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

async function generateManualForTheme(themePath: string, themeName: string): Promise<GeneratedManual | null> {
  try {
    console.log(`\nGenerating manual for theme: ${themeName}`);
    
    // Configure manual generation options
    const options: ManualGeneratorOptions = {
      themePath,
      themeName,
      includeSystemTests: true,
      includeUnitTests: true,
      includeIntegrationTests: true,
      outputFormat: ['markdown', 'html', 'json'],
      templateStyle: 'professional',
      includeScreenshots: false,
      generateTOC: true,
      includeSearchIndex: true,
      metadata: {
        project: 'AI Development Platform',
        version: '1.0.0',
        generatedAt: new Date().toISOString()
      }
    };
    
    // Initialize generator
    const generator = new ManualGenerator(options);
    
    // Generate manual
    const manual = await generator.generate();
    
    // Save outputs
    const themeOutputDir = path.join(OUTPUT_DIR, themeName);
    if (!fs.existsSync(themeOutputDir)) {
      fs.mkdirSync(themeOutputDir, { recursive: true });
    }
    
    // Save markdown version
    if (manual.markdown) {
      const mdPath = path.join(themeOutputDir, 'TEST_MANUAL.md');
      fs.writeFileSync(mdPath, manual.markdown);
      console.log(`  ✓ Generated: ${path.relative(process.cwd(), mdPath)}`);
    }
    
    // Save HTML version
    if (manual.html) {
      const htmlPath = path.join(themeOutputDir, 'test-manual.html');
      fs.writeFileSync(htmlPath, manual.html);
      console.log(`  ✓ Generated: ${path.relative(process.cwd(), htmlPath)}`);
    }
    
    // Save JSON version
    if (manual.json) {
      const jsonPath = path.join(themeOutputDir, 'test-manual.json');
      fs.writeFileSync(jsonPath, JSON.stringify(manual.json, null, 2));
      console.log(`  ✓ Generated: ${path.relative(process.cwd(), jsonPath)}`);
    }
    
    return manual;
  } catch (error) {
    console.error(`  ✗ Error generating manual for ${themeName}:`, error.message);
    return null;
  }
}

async function generateIndexManual(manuals: Map<string, GeneratedManual>) {
  console.log('\nGenerating master index manual...');
  
  let indexContent = `# Test Manual Index - AI Development Platform

Generated: ${new Date().toISOString()}

## Overview

This index provides access to test documentation for all themes in the AI Development Platform.

## Themes

`;

  // Add links to each theme's manual
  const sortedThemes = Array.from(manuals.keys()).sort();
  
  for (const themeName of sortedThemes) {
    const manual = manuals.get(themeName);
    if (manual) {
      const themeType = themeName.split('_')[0];
      const component = themeName.split('_')[1] || themeName;
      
      indexContent += `### ${themeName}\n`;
      indexContent += `- **Type**: ${themeType}\n`;
      indexContent += `- **Component**: ${component}\n`;
      indexContent += `- **Test Count**: ${manual.testCount || 0}\n`;
      indexContent += `- **Coverage**: ${manual.coverage || 'N/A'}\n`;
      indexContent += `- [View Manual](${themeName}/TEST_MANUAL.md)\n`;
      indexContent += `- [HTML Version](${themeName}/test-manual.html)\n`;
      indexContent += `\n`;
    }
  }
  
  // Add statistics
  indexContent += `## Statistics

- **Total Themes**: ${manuals.size}
- **Total Tests Documented**: ${Array.from(manuals.values()).reduce((sum, m) => sum + (m.testCount || 0), 0)}
- **Generation Date**: ${new Date().toLocaleDateString()}

## How to Use

1. Click on any theme link to view its test manual
2. Each manual contains:
   - Test descriptions
   - Test steps and expectations
   - Setup and teardown procedures
   - Data requirements
   - Environment configuration

## Manual Formats

Each theme has documentation in multiple formats:
- **Markdown (.md)** - For viewing in text editors and Git
- **HTML (.html)** - For viewing in browsers with navigation
- **JSON (.json)** - For programmatic access and automation

---
*Generated by test-as-manual system*
`;
  
  // Save index
  const indexPath = path.join(OUTPUT_DIR, 'INDEX.md');
  fs.writeFileSync(indexPath, indexContent);
  console.log(`  ✓ Generated index: ${path.relative(process.cwd(), indexPath)}`);
}

async function main() {
  console.log('========================================');
  console.log('Test-as-Manual Documentation Generator');
  console.log('========================================');
  
  try {
    // Initialize scanner
    const scanner = new ThemeScanner(THEMES_DIR);
    
    // Scan all themes
    console.log('\nScanning themes for test files...');
    const themes = await scanner.scanAll();
    console.log(`Found ${themes.length} themes with tests`);
    
    // Generate manuals for each theme
    const generatedManuals = new Map<string, GeneratedManual>();
    let successCount = 0;
    let failCount = 0;
    
    for (const theme of themes) {
      const themePath = path.join(THEMES_DIR, theme.name);
      const manual = await generateManualForTheme(themePath, theme.name);
      
      if (manual) {
        generatedManuals.set(theme.name, manual);
        successCount++;
      } else {
        failCount++;
      }
    }
    
    // Generate master index
    await generateIndexManual(generatedManuals);
    
    // Summary
    console.log('\n========================================');
    console.log('Generation Complete');
    console.log('========================================');
    console.log(`Successful: ${successCount} themes`);
    console.log(`Failed: ${failCount} themes`);
    console.log(`Output directory: ${path.relative(process.cwd(), OUTPUT_DIR)}`);
    console.log(`\nView the index at: ${path.relative(process.cwd(), path.join(OUTPUT_DIR, 'INDEX.md'))}`);
    
  } catch (error) {
    console.error('Fatal error:', error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main().catch(console.error);
}

export { generateManualForTheme, generateIndexManual };